# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin',
            field=models.CharField(default='user', max_length=15),
        ),
    ]
