# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20170317_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('December', 'December'), ('December', 'December')], default='January', max_length=10),
        ),
    ]
