# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_auto_20170317_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='day',
        ),
        migrations.RemoveField(
            model_name='user',
            name='month',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
    ]
