# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='course_id',
            new_name='course',
        ),
    ]
