# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_auto_20170311_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
