# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_auto_20170320_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
