# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='email',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='password',
        ),
    ]
